version: "3.8"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
